import './globals.css'
import type { Metadata } from 'next'
import Link from "next/link";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"relative m-0"}>
        <header className="p-10 lg:sticky top-0 lg:mb-10">
          <nav>
            <div className="text-2xl font-bold mb-4"><Link href="/" rel="logo">Andy Hunter</Link></div>
            <ul className="inline-flex sm:flex sm:flex-col space-x-2 sm:space-x-0">
              <li><Link href="/">index</Link></li>
              <li><Link href="/about">about</Link></li>
              <li><Link href="mailto: andyhunter52@gmail.com">contact</Link></li>
            </ul>
          </nav>
        </header>
        <main className="flex px-10 sm:p-10 lg:justify-center">
          {children}
        </main>
      </body>
    </html>
  )
}
